### ISSUE TITLE
Some minor improvements

### ISSUE THREAD

**Issue by jamartis** [aufover/experiments#1]
- Mention the csmock plugins
- Change the `-j<n>` to something more descriptive (e.g. `-j<number of jobs`>
- Descibe how exactly should the `--<tool>-add-flag` be used
- add copy-pasteable example

**Comment by lzaoral** [comment]
@vmihalko this can be closed, right?

**Comment by vmihalko** [comment]
certainly

**Comment by kdudka** [comment]
Thank you all for working on this!
